-- 1. QUERY TO DISPLAY LastName, DepartmentNumber and DepartmentName FOR ALL EMPLOYEES --
SELECT EMP.LAST_NAME, DEP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME 
FROM EMPLOYEES AS EMP JOIN DEPARTMENTS AS DEP 
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

-- 2. QUERY TO LIST UNIQUE JOBS IN DEPARTMENT 30 ALONG WITH LocationId --
SELECT DISTINCT EMP.JOB_ID, DEP.LOCATION_ID 
FROM EMPLOYEES AS EMP, DEPARTMENTS AS DEP
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
AND EMP.DEPARTMENT_ID=30;

-- 3. QUERY TO DISPLAY LastName, DepartmentName, Location_id and City OF ALL EMPLOYEES EARNING A COMMISSION --
SELECT EMP.LAST_NAME, DEP.DEPARTMENT_NAME, DEP.LOCATION_ID, LOC.CITY 
FROM EMPLOYEES AS EMP, DEPARTMENTS AS DEP, LOCATIONS AS LOC
WHERE EMP.DEPARTMENT_ID=DEP.DEPARTMENT_ID
AND DEP.LOCATION_ID=LOC.LOCATION_ID
AND EMP.COMMISSION_PCT IS NOT NULL;

-- 4. QUERY TO DISPLAY LastName, DepartmentName, LocationId and City OF EMPLOYEES HAVING 'a' IN THEIR LAST NAME --
SELECT EMP.LAST_NAME, DEP.DEPARTMENT_NAME, DEP.LOCATION_ID, LOC.CITY
FROM EMPLOYEES AS EMP, DEPARTMENTS AS DEP, LOCATIONS AS LOC
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
AND DEP.LOCATION_ID = LOC.LOCATION_ID
AND LAST_NAME LIKE '%a%';

-- 5. QUERY TO DISPLAY LastName, Job, DepartmentNumber and DepartmentName FOR EMPLOYEES WORKING IN TORONTO --
SELECT EMP.LAST_NAME, EMP.JOB_ID, EMP.DEPARTMENT_ID, DEP.DEPARTMENT_NAME
FROM EMPLOYEES AS EMP JOIN DEPARTMENTS AS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
JOIN LOCATIONS AS LOC
ON DEP.LOCATION_ID = LOC.LOCATION_ID
WHERE LOC.CITY='Toronto';

-- 6. QUERY TO DISPLAY LastName, EmployeeNumber, Manager's LastName and ManagerNumber as Employee, Emp#, Manager, Manager# --
SELECT EMP.LAST_NAME AS "EMPLOYEE", EMP.EMPLOYEE_ID AS "EMP#", MAG.LAST_NAME AS "MANAGER", MAG.EMPLOYEE_ID AS "MANAGER#"
FROM EMPLOYEES AS EMP
JOIN EMPLOYEES AS MAG
ON EMP.MANAGER_ID = MAG.EMPLOYEE_ID;

